export const LOCAL_STORAGE_USERS_KEY = "userSignUpInfoList";
export const LOCAL_STORAGE_LOGGED_USER_KEY = "userLoggedInInfo";


export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    FILTER_PRODUCTS: "FILTER_PRODUCTS",
    ADD_NEW_PRODUCTS:"ADD_NEW_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    SELECTED_PRODUCT:" SELECTED_PRODUCT",
    DELETE_FROM_CART:"DELETE_FROM_CART",
    UPDATE_CART:"UPDATE_CART",
   
};
 